version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./DockerDebugging101/Dockerfile
  another:
    build:
      context: ../
      dockerfile: ./DockerDebugging101.AnotherOne/Dockerfile